"""Signal type and risk level enumerations."""

from enum import Enum


class SignalType(str, Enum):
    """Trading signal types.

    This enum defines the possible trading signals that can be
    generated by the signal engine.
    """

    ENTER = "ENTER"
    WAIT = "WAIT"
    REDUCE = "REDUCE"
    EXIT = "EXIT"


class RiskLevel(str, Enum):
    """Risk level classifications.

    This enum defines the risk levels for trading signals.
    """

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"